[package]
name = "stratum-proxy"
version = "0.0.1"
authors = ["matt"]

[dependencies]
secp256k1 = "0.8"
bitcoin = "0.12"
bytes = "0.4"
futures = "0.1"
tokio = "0.1"
tokio-io = "0.1"
tokio-timer = "0.1"
rust-crypto = "0.2"
serde_json = "1.0"
