[package]
name = "mining-proxy"
version = "0.0.1"
authors = ["matt"]

[[bin]]
name = "mining-proxy"
path = "src/main.rs"

[[bin]]
name = "sample-pool"
path = "src/sample_pool.rs"

[dependencies]
secp256k1 = "0.9"
bitcoin = { path = "../rust-bitcoin" }
bytes = "0.4"
futures = "0.1"
tokio = "0.1"
tokio-io = "0.1"
tokio-threadpool = "0.1"
tokio-executor = "0.1"
rust-crypto = "0.2"
serde_json = "1.0"
